tbaseURL = "https://vincibooherlab.github.io/"
languageCode = "en-us"

[module]
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[menu]

  [[menu.header]]
  name = "Research"
  URL = "/research"
  weight = 2

  [[menu.header]]
  name = "Papers"
  URL = "/publications"
  weight = 3

  [[menu.header]]
  name = "Team"
  URL = "/team"
  weight = 4

  # [[menu.header]]
  # name = "News"
  # URL = "/news"
  # weight = 5

[params]

  googleMaps = ""
  googleTagManagerID = ""

  title = "Perception, Action, & Learning Lab"

  [params.logo]
    img = "/img/pestillilab-01.svg"
    alt = "Pestilli Lab"

  [params.footer]

    title = "Perception, Action, & Learning Lab"
    address = [
      "Dept. of Psychology & Human Development",
      "Vanderbilt University",
      "Peabody #552",
      "230 Appleton Place",
      "Nashville, TN, 37212",
    ]

    backgroundColor = "#F8F8F8"
    textColor = "#000"
    sectionColor = "#333"
    iconsColor = "#444"

    [params.footer.logo]
      img = "/img/pestillilab-02.svg"
      alt = "Pestilli Lab"

    [params.footer.RelatedLinks]

      [params.footer.RelatedLinks.Education]
          "Psychology PHD" = "https://peabody.vanderbilt.edu/departments/psych/"
          "Neuroscience PHD" = "https://medschool.vanderbilt.edu/brain-institute/new-vbi-homepage-inprogress/join-our-graduate-program/educational-neuroscience/"
          
      [params.footer.RelatedLinks.Research]
          # insert link to MRItablet development: "NeuroscienceNetwork.org" = "https://neurosciencenetwork.org"
          "brainlife.io" = "https://brainlife.io"

      [params.footer.Institutional]
          "Peabody College" = "https://liberalarts.utexas.edu/psychology"
          "Vanderbilt Brain Institute" = "https://medschool.vanderbilt.edu/brain-institute/"
          "Vanderbilt University Institute of Imaging Science " = "https://vuiis.vumc.org/"
          "ACCRE" = "https://www.vanderbilt.edu/accre/"
